### ISSUE TITLE
No such file or directory - ../data/company_infos.yml (Errno::ENOENT)

### ISSUE THREAD

**Issue by pcambra** [lauriii/drupalcores#41]
Where are these YAML files? company_mapping and company_infos, I'm guessing they're created by companies.rb but I'm getting the error running companyinfo or buildcompanies

**Comment by pcambra** [comment]
I'm still getting the error, but way later:

```
./companies.rb:146:in `initialize': No such file or directory - ../data/company_infos.yml (Errno::ENOENT)
	from ./companies.rb:146:in `open'
	from ./companies.rb:146:in `<main>'
[20:40:22] 'buildcompanies' errored after 1.55 h
[20:40:22] Error in plugin 'gulp-shell'
Message:
    Command failed: ./companies.rb:146:in `initialize': No such file or directory - ../data/company_infos.yml (Errno::ENOENT)
	from ./companies.rb:146:in `open'
	from ./companies.rb:146:in `<main>'

Details:
    killed: false
    code: 1
    signal: null
    stdout: 
    stderr: ./companies.rb:146:in `initialize': No such file or directory - ../data/company_infos.yml (Errno::ENOENT)
	from ./companies.rb:146:in `open'
	from ./companies.rb:146:in `<main>'

[20:40:22] 'default' errored after 1.57 h

**Comment by pcambra** [comment]
Opened #46 for this
